title: Andrew Wang's Portfolio
description: Andrew Wang's personal website and data science portfolio

# enabled baseurl if you are using project pages in Github or Gitlab
#baseurl: /figs

# TODO: remove blog path and works path?
permalink: /blog/:title/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

collections:
  works:
    output: true
    permalink: /research/:path/
  personal:
    output: true
    permalink: /personal/:path/

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]